# Generated by Django 3.2 on 2024-05-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_unique_author_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(
                through='reviews.GenreTitle', to='reviews.Genre'),
        ),
        migrations.DeleteModel(
            name='GenreTitle',
        ),
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(to='reviews.Genre'),
        ),
    ]
